name: Hola Mundo

on:
  push:
    branches: [ lab03 ]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Decir Hola
        run: echo "¡Hola mundo de tuberías!"
      
      - name: Mostrar información del corredor
        run: |
          echo "Ejecutándose en: $(uname -a)"
          echo "Flujo de trabajo: ${{ github.workflow }}"
          echo "Activado por: ${{ github.event_name }}"
          echo "Repositorio: ${{ github.repository }}"
