name: Hola Mundo

on:
  push:
    branches: [ lab03 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v6

      - name: Configurar pnpm
        uses: pnpm/action-setup@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm

      - name: Ejecutar script lab2
        run: ./deliverables/lab02/lab2.sh
